### ISSUE TITLE
PDF file

### ISSUE THREAD

**Issue by sedv8808** [UBC-MDS/Song_Key_Mode_and_Popularity_on_Spotify#44]
Hi @Pall-v 

I noticed you changed the report output to just be an html file.

From my understanding, there has to be a pdf file as an output... I am wondering if having a pdf has issues with any of the knitting commands you chose and this is why you decided to change the output? If so, let me know so that we can document this and delete the previous pdf file that lingers in the reports file.

**Comment by Pall-v** [comment]
I included the HTML so that you could see the effect of the change without running the scripts, but they should still produce the pdf file.  There is a problem with the figure size in the new pdf that I am still trying to fix so that is why I didn't include the pdf output.
